# Generated by Django 5.2.6 on 2025-09-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="excluded_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags qui ne seront pas affichés dans le frontend mais restent en base de données",
                related_name="excluded_from_projects",
                to="testing.tag",
                verbose_name="Tags exclus",
            ),
        ),
        migrations.AddField(
            model_name="projectfeature",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="projects.project",
                verbose_name="Projet",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectfeature",
            unique_together={("project", "feature_key")},
        ),
    ]
