# Generated by Django 5.2.5 on 2025-09-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="excluded_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags qui ne seront pas affichés dans le frontend mais restent en base de données",
                related_name="excluded_from_projects",
                to="testing.tag",
                verbose_name="Tags exclus",
            ),
        ),
    ]
