# Generated by Django 5.2.6 on 2025-09-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserContext",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modifié le")),
            ],
            options={
                "verbose_name": "Contexte utilisateur",
                "verbose_name_plural": "Contextes utilisateurs",
            },
        ),
    ]
