# Generated by Django 5.2.6 on 2025-09-18 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Si aucun projet n'est sélectionné, l'utilisateur accède à tous les projets",
                to="projects.project",
                verbose_name="Projets accessibles",
            ),
        ),
        migrations.AddField(
            model_name="usercontext",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Utilisateur"
            ),
        ),
    ]
