# Generated by Django 5.2.5 on 2025-09-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du tag')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Couleur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['project__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre du test')),
                ('file_path', models.CharField(max_length=500, verbose_name='Chemin du fichier')),
                ('line', models.IntegerField(verbose_name='Ligne')),
                ('column', models.IntegerField(verbose_name='Colonne')),
                ('test_id', models.CharField(blank=True, max_length=100, verbose_name='ID du test')),
                ('story', models.TextField(blank=True, verbose_name='Histoire/Description')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='projects.project', verbose_name='Projet')),
                ('tags', models.ManyToManyField(blank=True, to='testing.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ['file_path', 'line'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_file', models.CharField(blank=True, max_length=500, verbose_name='Fichier de configuration')),
                ('root_dir', models.CharField(blank=True, max_length=500, verbose_name='Répertoire racine')),
                ('playwright_version', models.CharField(blank=True, max_length=50, verbose_name='Version Playwright')),
                ('workers', models.IntegerField(default=1, verbose_name='Nombre de workers')),
                ('actual_workers', models.IntegerField(default=1, verbose_name='Workers réels')),
                ('git_commit_hash', models.CharField(blank=True, max_length=40, verbose_name='Hash du commit')),
                ('git_commit_short_hash', models.CharField(blank=True, max_length=10, verbose_name='Hash court du commit')),
                ('git_branch', models.CharField(blank=True, max_length=200, verbose_name='Branche Git')),
                ('git_commit_subject', models.TextField(blank=True, verbose_name='Sujet du commit')),
                ('git_author_name', models.CharField(blank=True, max_length=200, verbose_name='Auteur')),
                ('git_author_email', models.EmailField(blank=True, max_length=254, verbose_name='Email auteur')),
                ('ci_build_href', models.URLField(blank=True, verbose_name='Lien vers le build CI')),
                ('ci_commit_href', models.URLField(blank=True, verbose_name='Lien vers le commit CI')),
                ('start_time', models.DateTimeField(verbose_name="Début d'exécution")),
                ('duration', models.FloatField(verbose_name='Durée (ms)')),
                ('expected_tests', models.IntegerField(default=0, verbose_name='Tests attendus')),
                ('skipped_tests', models.IntegerField(default=0, verbose_name='Tests ignorés')),
                ('unexpected_tests', models.IntegerField(default=0, verbose_name='Tests inattendus')),
                ('flaky_tests', models.IntegerField(default=0, verbose_name='Tests instables')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Importé le')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('raw_json', models.JSONField(help_text='Données JSON complètes', verbose_name='JSON brut')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Exécution de tests',
                'verbose_name_plural': 'Exécutions de tests',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50, verbose_name='ID projet Playwright')),
                ('project_name', models.CharField(max_length=200, verbose_name='Nom projet Playwright')),
                ('timeout', models.IntegerField(verbose_name='Timeout (ms)')),
                ('expected_status', models.CharField(max_length=20, verbose_name='Statut attendu')),
                ('status', models.CharField(choices=[('passed', 'Passé'), ('failed', 'Échoué'), ('skipped', 'Ignoré'), ('flaky', 'Instable'), ('expected', 'Attendu'), ('unexpected', 'Inattendu')], max_length=20, verbose_name='Statut')),
                ('worker_index', models.IntegerField(verbose_name='Index du worker')),
                ('parallel_index', models.IntegerField(verbose_name='Index parallèle')),
                ('duration', models.FloatField(verbose_name='Durée (ms)')),
                ('retry', models.IntegerField(default=0, verbose_name='Tentative')),
                ('start_time', models.DateTimeField(verbose_name='Début')),
                ('errors', models.JSONField(default=list, verbose_name='Erreurs')),
                ('stdout', models.JSONField(default=list, verbose_name='Sortie standard')),
                ('stderr', models.JSONField(default=list, verbose_name="Sortie d'erreur")),
                ('steps', models.JSONField(default=list, verbose_name='Étapes')),
                ('annotations', models.JSONField(default=list, verbose_name='Annotations')),
                ('attachments', models.JSONField(default=list, verbose_name='Pièces jointes')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='testing.testexecution', verbose_name='Exécution')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testing.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Résultat de test',
                'verbose_name_plural': 'Résultats de tests',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('color', 'project'), name='unique_color_per_project', violation_error_message='Cette couleur est déjà utilisée pour un autre tag de ce projet.'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('color', 'project'), ('name', 'project')},
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(condition=models.Q(('test_id__isnull', False), models.Q(('test_id', ''), _negated=True)), fields=('project', 'test_id'), name='unique_test_id_per_project'),
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('project', 'title', 'file_path', 'line', 'column')},
        ),
    ]
