# Generated by Django 5.2.5 on 2025-09-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CIConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Nom de la configuration")),
                (
                    "provider",
                    models.CharField(
                        choices=[("gitlab", "GitLab"), ("github", "GitHub")], max_length=20, verbose_name="Fournisseur CI"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modifié le")),
            ],
            options={
                "verbose_name": "Configuration CI",
                "verbose_name_plural": "Configurations CI",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GitHubConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("repository", models.CharField(help_text="Format: owner/repo", max_length=200, verbose_name="Repository")),
                (
                    "access_token",
                    models.CharField(
                        help_text="GitHub Personal Access Token. ⚠️ Sera stocké de manière sécurisée et masqué dans l'interface.",
                        max_length=200,
                        verbose_name="Token d'accès",
                    ),
                ),
                (
                    "workflow_name",
                    models.CharField(
                        help_text="Nom du workflow GitHub Actions", max_length=200, verbose_name="Nom du workflow"
                    ),
                ),
                (
                    "artifact_name",
                    models.CharField(
                        help_text="Nom de l'artifact contenant les résultats", max_length=200, verbose_name="Nom de l'artifact"
                    ),
                ),
                (
                    "json_filename",
                    models.CharField(
                        help_text="Nom du fichier JSON dans l'artifact", max_length=200, verbose_name="Nom du fichier JSON"
                    ),
                ),
                (
                    "ci_config",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_config",
                        to="integrations.ciconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration GitHub",
                "verbose_name_plural": "Configurations GitHub",
            },
        ),
        migrations.CreateModel(
            name="GitLabConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gitlab_url", models.URLField(help_text="Ex: https://gitlab.com", verbose_name="URL GitLab")),
                ("project_id", models.CharField(max_length=100, verbose_name="ID du projet GitLab")),
                (
                    "access_token",
                    models.CharField(
                        help_text="Token avec permissions API. ⚠️ Sera stocké de manière sécurisée et masqué dans l'interface.",
                        max_length=200,
                        verbose_name="Token d'accès",
                    ),
                ),
                (
                    "job_name",
                    models.CharField(
                        help_text="Nom du job contenant les artifacts", max_length=200, verbose_name="Nom du job"
                    ),
                ),
                (
                    "artifact_path",
                    models.CharField(
                        help_text="Chemin du fichier JSON dans les artifacts",
                        max_length=500,
                        verbose_name="Chemin vers le JSON",
                    ),
                ),
                (
                    "ci_config",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gitlab_config",
                        to="integrations.ciconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration GitLab",
                "verbose_name_plural": "Configurations GitLab",
            },
        ),
    ]
