name: Deploy to Main

# Déploiement automatique quand on push sur main
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  # Tests finaux avant déploiement
  final-tests:
    runs-on: ubuntu-latest
    steps:
    - name: 🔄 Checkout du code
      uses: actions/checkout@v4
    
    - name: 🐍 Configuration de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: 📥 Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 🧪 Tests complets
      run: |
        python manage.py test --verbosity=2 --parallel
      env:
        DJANGO_SETTINGS_MODULE: pw_analyst.settings
    
    - name: 🏗️ Test de collecte des fichiers statiques
      run: |
        python manage.py collectstatic --noinput --verbosity=0
      env:
        DJANGO_SETTINGS_MODULE: pw_analyst.settings
    
    - name: ✅ Validation du déploiement
      run: |
        echo "✅ Tous les tests passent sur main"
        echo "🚀 Prêt pour le déploiement"

  # Créer un tag de version automatiquement
  create-release-tag:
    runs-on: ubuntu-latest
    needs: final-tests
    if: success()
    steps:
    - name: 🔄 Checkout du code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: 🏷️ Génération automatique de tag
      id: tag_version
      run: |
        # Récupère le dernier tag
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "Dernier tag: $LAST_TAG"
        
        # Extrait le numéro de version
        VERSION=${LAST_TAG#v}
        IFS='.' read -ra ADDR <<< "$VERSION"
        MAJOR=${ADDR[0]:-0}
        MINOR=${ADDR[1]:-0}
        PATCH=${ADDR[2]:-0}
        
        # Incrémente le patch
        PATCH=$((PATCH + 1))
        NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
        
        echo "Nouvelle version: $NEW_VERSION"
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        
        # Crée le tag
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION - Auto-generated"
        git push origin "$NEW_VERSION"
    
    - name: 📋 Création de release GitHub
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.version }}
        release_name: Release ${{ steps.tag_version.outputs.version }}
        body: |
          🚀 **Release automatique après merge sur main**
          
          **Changements :**
          - Tests Django : ✅ Passés
          - Vérifications de sécurité : ✅ Validées
          - Migrations : ✅ Validées
          
          **Hash du commit :** `${{ github.sha }}`
          **Date :** ${{ github.event.head_commit.timestamp }}
          
          Cette release a été créée automatiquement après validation de tous les tests.
        draft: false
        prerelease: false

  # Notification de succès
  notify-success:
    runs-on: ubuntu-latest
    needs: [final-tests, create-release-tag]
    if: always() && needs.final-tests.result == 'success'
    steps:
    - name: 🎉 Notification de succès
      run: |
        echo "## 🎉 Déploiement Main Réussi" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ **Tests :** Tous passés" >> $GITHUB_STEP_SUMMARY
        echo "🏷️ **Version :** ${{ needs.create-release-tag.outputs.version || 'Tag non créé' }}" >> $GITHUB_STEP_SUMMARY
        echo "📅 **Date :** $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_STEP_SUMMARY
        echo "🔗 **Commit :** [\`${{ github.sha }}\`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "🚀 L'application est maintenant déployée sur main avec succès !" >> $GITHUB_STEP_SUMMARY